mailinglist: MLMMJ

credentials:
  # Medlemsnummer er brugernavn:
  user: 123456
  password: correcthorsebatterystaple

# Credentials can also be specified in ~/.netrc:
# machine medlem.dds.dk login 123456 password correcthorsebatterystaple

odoo:
  # Zend\Http\Client httpOptions. I.e. timeout:
  client_options:
    timeout: 10

mlmmj:
  # Sudo, ssh, whatever to get to the /usr/bin/mlmmj-* binaries (remember trailing space):
  command_prefix: 'ssh mail.example.net '
